# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/UDRC_HW/workspaces/vivado2021.2/PR_Test04/PR_Test04.gen/sources_1/bd/design_1/bd/bram_update0_inst_0/ip/bram_update0_inst_0_axi_bram_ctrl_0_bram_0/bram_update0_inst_0_axi_bram_ctrl_0_bram_0.xci
# IP: The module: 'bram_update0_inst_0_axi_bram_ctrl_0_bram_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/UDRC_HW/workspaces/vivado2021.2/PR_Test04/PR_Test04.gen/sources_1/bd/design_1/bd/bram_update0_inst_0/ip/bram_update0_inst_0_axi_bram_ctrl_0_bram_0/bram_update0_inst_0_axi_bram_ctrl_0_bram_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_update0_inst_0_axi_bram_ctrl_0_bram_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: e:/UDRC_HW/workspaces/vivado2021.2/PR_Test04/PR_Test04.gen/sources_1/bd/design_1/bd/bram_update0_inst_0/ip/bram_update0_inst_0_axi_bram_ctrl_0_bram_0/bram_update0_inst_0_axi_bram_ctrl_0_bram_0.xci
# IP: The module: 'bram_update0_inst_0_axi_bram_ctrl_0_bram_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/UDRC_HW/workspaces/vivado2021.2/PR_Test04/PR_Test04.gen/sources_1/bd/design_1/bd/bram_update0_inst_0/ip/bram_update0_inst_0_axi_bram_ctrl_0_bram_0/bram_update0_inst_0_axi_bram_ctrl_0_bram_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_update0_inst_0_axi_bram_ctrl_0_bram_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
