# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/UDRC_HW/workspaces/vivado2021.2/PR_Test03/PR_Test03.gen/sources_1/bd/design_1/bd/ram_blk0_inst_0/ip/ram_blk0_inst_0_axi_bram_ctrl_0_0/ram_blk0_inst_0_axi_bram_ctrl_0_0.xci
# IP: The module: 'ram_blk0_inst_0_axi_bram_ctrl_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/UDRC_HW/workspaces/vivado2021.2/PR_Test03/PR_Test03.gen/sources_1/bd/design_1/bd/ram_blk0_inst_0/ip/ram_blk0_inst_0_axi_bram_ctrl_0_0/ram_blk0_inst_0_axi_bram_ctrl_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ram_blk0_inst_0_axi_bram_ctrl_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: E:/UDRC_HW/workspaces/vivado2021.2/PR_Test03/PR_Test03.gen/sources_1/bd/design_1/bd/ram_blk0_inst_0/ip/ram_blk0_inst_0_axi_bram_ctrl_0_0/ram_blk0_inst_0_axi_bram_ctrl_0_0.xci
# IP: The module: 'ram_blk0_inst_0_axi_bram_ctrl_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/UDRC_HW/workspaces/vivado2021.2/PR_Test03/PR_Test03.gen/sources_1/bd/design_1/bd/ram_blk0_inst_0/ip/ram_blk0_inst_0_axi_bram_ctrl_0_0/ram_blk0_inst_0_axi_bram_ctrl_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ram_blk0_inst_0_axi_bram_ctrl_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
