# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: e:/UDRC_HW/workspaces/vivado2021.2/PR_Test03/PR_Test03.gen/sources_1/bd/design_1/bd/ram_update0_inst_0/ram_update0_inst_0.bd
# Block Designs: The module: 'ram_update0_inst_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: e:/UDRC_HW/workspaces/vivado2021.2/PR_Test03/PR_Test03.gen/sources_1/bd/design_1/bd/ram_update0_inst_0/ip/ram_update0_inst_0_axi_bram_ctrl_0_0/ram_update0_inst_0_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ram_update0_inst_0_axi_bram_ctrl_0_0 || ORIG_REF_NAME==ram_update0_inst_0_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: e:/UDRC_HW/workspaces/vivado2021.2/PR_Test03/PR_Test03.gen/sources_1/bd/design_1/bd/ram_update0_inst_0/ip/ram_update0_inst_0_axi_bram_ctrl_0_bram_0/ram_update0_inst_0_axi_bram_ctrl_0_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ram_update0_inst_0_axi_bram_ctrl_0_bram_0 || ORIG_REF_NAME==ram_update0_inst_0_axi_bram_ctrl_0_bram_0} -quiet] -quiet

# XDC: e:/UDRC_HW/workspaces/vivado2021.2/PR_Test03/PR_Test03.gen/sources_1/bd/design_1/bd/ram_update0_inst_0/ram_update0_inst_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ram_update0_inst_0'. Do not add the DONT_TOUCH constraint.

# Block Designs: e:/UDRC_HW/workspaces/vivado2021.2/PR_Test03/PR_Test03.gen/sources_1/bd/design_1/bd/ram_update0_inst_0/ram_update0_inst_0.bd
# Block Designs: The module: 'ram_update0_inst_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: e:/UDRC_HW/workspaces/vivado2021.2/PR_Test03/PR_Test03.gen/sources_1/bd/design_1/bd/ram_update0_inst_0/ip/ram_update0_inst_0_axi_bram_ctrl_0_0/ram_update0_inst_0_axi_bram_ctrl_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ram_update0_inst_0_axi_bram_ctrl_0_0 || ORIG_REF_NAME==ram_update0_inst_0_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: e:/UDRC_HW/workspaces/vivado2021.2/PR_Test03/PR_Test03.gen/sources_1/bd/design_1/bd/ram_update0_inst_0/ip/ram_update0_inst_0_axi_bram_ctrl_0_bram_0/ram_update0_inst_0_axi_bram_ctrl_0_bram_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ram_update0_inst_0_axi_bram_ctrl_0_bram_0 || ORIG_REF_NAME==ram_update0_inst_0_axi_bram_ctrl_0_bram_0} -quiet] -quiet

# XDC: e:/UDRC_HW/workspaces/vivado2021.2/PR_Test03/PR_Test03.gen/sources_1/bd/design_1/bd/ram_update0_inst_0/ram_update0_inst_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ram_update0_inst_0'. Do not add the DONT_TOUCH constraint.
