# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/UDRC_HW/workspaces/vivado2021.2/PR_Test04/PR_Test04.srcs/sources_1/bd/bram_blk0/ip/bram_blk0_blk_mem_gen_0_0/bram_blk0_blk_mem_gen_0_0.xci
# IP: The module: 'bram_blk0_blk_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/UDRC_HW/workspaces/vivado2021.2/PR_Test04/PR_Test04.gen/sources_1/bd/bram_blk0/ip/bram_blk0_blk_mem_gen_0_0/bram_blk0_blk_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_blk0_blk_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: e:/UDRC_HW/workspaces/vivado2021.2/PR_Test04/PR_Test04.srcs/sources_1/bd/bram_blk0/ip/bram_blk0_blk_mem_gen_0_0/bram_blk0_blk_mem_gen_0_0.xci
# IP: The module: 'bram_blk0_blk_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/UDRC_HW/workspaces/vivado2021.2/PR_Test04/PR_Test04.gen/sources_1/bd/bram_blk0/ip/bram_blk0_blk_mem_gen_0_0/bram_blk0_blk_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_blk0_blk_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
